// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v5.29.3
// source: event.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Empty } from "./google/protobuf/empty.pb";

export const protobufPackage = "event";

export enum EventStatus {
  EVENT_STATUS_UNSPECIFIED = 0,
  EVENT_STATUS_DRAFT = 1,
  EVENT_STATUS_PUBLISHED = 2,
  EVENT_STATUS_CANCELLED = 3,
  EVENT_STATUS_CONFIGURED = 4,
  EVENT_STATUS_APPROVED = 5,
  UNRECOGNIZED = -1,
}

export enum EventRoleType {
  EVENT_ROLE_TYPE_UNSPECIFIED = 0,
  EVENT_ROLE_TYPE_ADMIN = 1,
  EVENT_ROLE_TYPE_EDITOR = 2,
  EVENT_ROLE_TYPE_VIEWER = 3,
  UNRECOGNIZED = -1,
}

export interface Event {
  id: string;
  name: string;
  description: string;
  startDate: string;
  endDate: string;
  thumbnailUrl: string;
  location: EventLocation | undefined;
  config: EventConfig | undefined;
  organizer: EventOrganizer | undefined;
  roles: EventRole[];
  categories: EventCategory[];
  status: EventStatus;
  createdAt: string;
  updatedAt: string;
}

export interface EventCategory {
  id: string;
  name: string;
}

export interface EventConfig {
  id: string;
  ticketSaleStartDate: string;
  ticketSaleEndDate: string;
  isFree: boolean;
  maxAttendees: number;
  isPublic: boolean;
  requiresApproval: boolean;
  allowWaitRoom: boolean;
  isNewTrending: boolean;
}

export interface EventLocation {
  id: string;
  venue: string;
  address: string;
}

export interface EventOrganizer {
  id: string;
  name: string;
  description: string;
  logoUrl: string;
}

export interface EventRole {
  id: string;
  userId: string;
  eventId: string;
  role: EventRoleType;
}

export interface CreateEventRequest {
  name: string;
  description: string;
  startDate: string;
  endDate: string;
  thumbnailUrl: string;
  venue: string;
  street: string;
  city: string;
  country: string;
  ward?: string | undefined;
  district?: string | undefined;
  categoryIds: string[];
  organizerName: string;
  organizerDescription: string;
  organizerLogoUrl: string;
  creatorUserId: string;
}

export interface CreateEventResponse {
  event: Event | undefined;
}

export interface UpdateEventRequest {
  id: string;
  name?: string | undefined;
  description?: string | undefined;
  startDate?: string | undefined;
  endDate?: string | undefined;
  thumbnailUrl?: string | undefined;
  venueName?: string | undefined;
  street?: string | undefined;
  city?: string | undefined;
  country?: string | undefined;
  ward?: string | undefined;
  district?: string | undefined;
  categoryIds: string[];
  organizerName?: string | undefined;
  organizerDescription?: string | undefined;
  organizerLogoUrl?: string | undefined;
  userId: string;
}

export interface UpdateEventResponse {
  event: Event | undefined;
}

export interface FindOneEventRequest {
  id: string;
}

export interface FindOneEventResponse {
  event: Event | undefined;
}

export interface EventFilter {
  searchQuery?: string | undefined;
  categoryIds: string[];
  status?: EventStatus | undefined;
  organizerId?: string | undefined;
  userId?: string | undefined;
  startDateFrom?: string | undefined;
  startDateTo?: string | undefined;
  city?: string | undefined;
  country?: string | undefined;
  isPublic?: boolean | undefined;
  isFree?: boolean | undefined;
}

export interface FindManyEventRequest {
  page: number;
  pageSize: number;
  filter?: EventFilter | undefined;
}

export interface FindManyEventResponse {
  events: Event[];
  pagination: PaginationInfo | undefined;
}

export interface PaginationInfo {
  page: number;
  pageSize: number;
  count: number;
  lastPage: number;
  hasNext: boolean;
  hasPrevious: boolean;
}

export interface ListEventRequest {
  filter?: EventFilter | undefined;
}

export interface ListEventResponse {
  events: Event[];
}

export interface DeleteEventRequest {
  id: string;
}

/** Event Config messages */
export interface CreateEventConfigRequest {
  userId: string;
  eventId: string;
  ticketSaleStartDate: string;
  ticketSaleEndDate: string;
  isFree: boolean;
  maxAttendees: number;
  isPublic: boolean;
  requiresApproval: boolean;
  allowWaitRoom: boolean;
  isNewTrending: boolean;
}

export interface CreateEventConfigResponse {
  eventConfig: EventConfig | undefined;
}

export interface GetEventConfigRequest {
  eventId: string;
  userId: string;
}

export interface GetEventConfigResponse {
  eventConfig: EventConfig | undefined;
}

export interface UpdateEventConfigRequest {
  eventId: string;
  userId: string;
  ticketSaleStartDate: string;
  ticketSaleEndDate: string;
  isFree: boolean;
  maxAttendees: number;
  isPublic: boolean;
  requiresApproval: boolean;
  allowWaitRoom: boolean;
  isNewTrending: boolean;
}

export interface UpdateEventConfigResponse {
  eventConfig: EventConfig | undefined;
}

export interface ApproveEventRequest {
  eventId: string;
  userId: string;
}

export interface PublishEventRequest {
  eventId: string;
  userId: string;
}

export interface CancelEventRequest {
  eventId: string;
  userId: string;
}

export interface CancelEventResponse {
  event: Event | undefined;
}

export interface GetEventRolesRequest {
  eventId: string;
}

export interface GetEventRolesResponse {
  roles: EventRole[];
}

export interface AssignEventRoleRequest {
  eventId: string;
  userId: string;
  role: EventRoleType;
}

export interface AssignEventRoleResponse {
  role: EventRole | undefined;
}

export interface RemoveEventRoleRequest {
  eventId: string;
  userId: string;
}

export const EVENT_PACKAGE_NAME = "event";

export interface EventServiceClient {
  create(request: CreateEventRequest): Observable<CreateEventResponse>;

  update(request: UpdateEventRequest): Observable<UpdateEventResponse>;

  findOne(request: FindOneEventRequest): Observable<FindOneEventResponse>;

  findMany(request: FindManyEventRequest): Observable<FindManyEventResponse>;

  list(request: ListEventRequest): Observable<ListEventResponse>;

  delete(request: DeleteEventRequest): Observable<Empty>;

  /** Event config */

  createConfig(request: CreateEventConfigRequest): Observable<CreateEventConfigResponse>;

  getConfig(request: GetEventConfigRequest): Observable<GetEventConfigResponse>;

  updateConfig(request: UpdateEventConfigRequest): Observable<UpdateEventConfigResponse>;

  /** Additional event-specific operations */

  approveEvent(request: ApproveEventRequest): Observable<Empty>;

  publishEvent(request: PublishEventRequest): Observable<Empty>;

  cancelEvent(request: CancelEventRequest): Observable<Empty>;

  getEventRoles(request: GetEventRolesRequest): Observable<GetEventRolesResponse>;

  assignEventRole(request: AssignEventRoleRequest): Observable<AssignEventRoleResponse>;

  removeEventRole(request: RemoveEventRoleRequest): Observable<Empty>;
}

export interface EventServiceController {
  create(
    request: CreateEventRequest,
  ): Promise<CreateEventResponse> | Observable<CreateEventResponse> | CreateEventResponse;

  update(
    request: UpdateEventRequest,
  ): Promise<UpdateEventResponse> | Observable<UpdateEventResponse> | UpdateEventResponse;

  findOne(
    request: FindOneEventRequest,
  ): Promise<FindOneEventResponse> | Observable<FindOneEventResponse> | FindOneEventResponse;

  findMany(
    request: FindManyEventRequest,
  ): Promise<FindManyEventResponse> | Observable<FindManyEventResponse> | FindManyEventResponse;

  list(request: ListEventRequest): Promise<ListEventResponse> | Observable<ListEventResponse> | ListEventResponse;

  delete(request: DeleteEventRequest): void;

  /** Event config */

  createConfig(
    request: CreateEventConfigRequest,
  ): Promise<CreateEventConfigResponse> | Observable<CreateEventConfigResponse> | CreateEventConfigResponse;

  getConfig(
    request: GetEventConfigRequest,
  ): Promise<GetEventConfigResponse> | Observable<GetEventConfigResponse> | GetEventConfigResponse;

  updateConfig(
    request: UpdateEventConfigRequest,
  ): Promise<UpdateEventConfigResponse> | Observable<UpdateEventConfigResponse> | UpdateEventConfigResponse;

  /** Additional event-specific operations */

  approveEvent(request: ApproveEventRequest): void;

  publishEvent(request: PublishEventRequest): void;

  cancelEvent(request: CancelEventRequest): void;

  getEventRoles(
    request: GetEventRolesRequest,
  ): Promise<GetEventRolesResponse> | Observable<GetEventRolesResponse> | GetEventRolesResponse;

  assignEventRole(
    request: AssignEventRoleRequest,
  ): Promise<AssignEventRoleResponse> | Observable<AssignEventRoleResponse> | AssignEventRoleResponse;

  removeEventRole(request: RemoveEventRoleRequest): void;
}

export function EventServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "create",
      "update",
      "findOne",
      "findMany",
      "list",
      "delete",
      "createConfig",
      "getConfig",
      "updateConfig",
      "approveEvent",
      "publishEvent",
      "cancelEvent",
      "getEventRoles",
      "assignEventRole",
      "removeEventRole",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("EventService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("EventService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const EVENT_SERVICE_NAME = "EventService";
